---
#
# SPDX-License-Identifier: GPL-3.0-or-later

default:
  image: "archlinux:latest"

stages:
  - lint

.unit_test:
  stage: lint
  before_script:
    - pacman --noconfirm -Syu --needed base-devel python-poetry python-tox

linter:
  extends: .unit_test
  script:
    - tox -e linter

coverage:
  extends: .unit_test
  script:
    - tox -e coverage
