[tool.poetry]
name = "arch-repo-management"
version = "0.1.0"
description = "Tools for package repository management"
authors = ["Arch Linux <arch-projects@lists.archlinux.org>"]
license = "GPL-3.0-or-later"
packages = [
  {include = 'repo_management'}
]
include = [
  {path = 'tests/*', format = 'sdist'}
]

[tool.poetry.dependencies]
python = "^3.10"
pyalpm = "^0.10.6"
pydantic = "^1.8.1"
orjson = "^3.5.1"
Jinja2 = "^2.11.3"
subprocess-tee = "^0.2.0"
aiofiles = "^0.6.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
tox = "^3.24.0"
pytest = "^6.2.2"
isort = "^5.10.0"
mypy = "^0.910"
flake8 = "^4.0.0"
black = "^21.12b0"
coverage = "^6.1"
mock = "^4.0.3"
pytest-asyncio = "^0.16.0"

[tool.poetry.scripts]
db2json = "repo_management.cli:db2json"
json2db = "repo_management.cli:json2db"

[tool.pytest.ini_options]
markers = ["integration"]

[tool.black]
line-length = 120
exclude = '''
/(
  \.direnv|
  |\.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |\.svn
  |_build
  |buck-out
  |db-write
  |db2json
  |dbscripts
  |build
  |dist
)/
'''


[tool.coverage.path]
source = "repo_management"

[tool.coverage.report]
omit = ["tests/*", ".tox/*", "db-write/*", "db2json/*", "dbscripts/*"]
precision = 2
show_missing = true

[tool.coverage.run]
branch = true
command_line = "-m pytest -v tests/ -m 'not integration'"
omit = ["tests/*", ".tox/*", "db-write/*", "db2json/*", "dbscripts/*"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
follow_imports_for_stubs = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
no_implicit_optional = true
warn_unreachable = true
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
