[tool.poetry]
name = "arch-repo-management"
version = "0.1.0"
description = "Tools for package repository management"
authors = ["Arch Linux <arch-projects@lists.archlinux.org>"]
license = "GPL-3.0-or-later"
packages = [
  {include = 'repo_management'},
  {include = 'tests', format = 'sdist'},
]

[tool.poetry.dependencies]
python = "^3.9"
pyalpm = "^0.9.2"
pydantic = "^1.8.1"
orjson = "^3.5.1"
Jinja2 = "^2.11.3"
subprocess-tee = "^0.2.0"

[tool.poetry.dev-dependencies]
tox = "^3.23.0"
pytest = "^6.2.2"
isort = "^5.7.0"
mypy = "^0.812"
flake8 = "^3.8.4"
black = "^20.8b1"
coverage = "^5.5"
mock = "^4.0.3"

[tool.poetry.scripts]
db2json = "repo_management.cli:db2json"
json2db = "repo_management.cli:json2db"

[tool.pytest.ini_options]
markers = ["integration"]

[tool.black]
line-length = 120
exclude = '''
/(
  \.direnv|
  |\.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |\.svn
  |_build
  |buck-out
  |db-write
  |db2json
  |dbscripts
  |build
  |dist
)/
'''


[tool.coverage.path]
source = "repo_management"

[tool.coverage.report]
omit = ["tests/*", ".tox/*", "db-write/*", "db2json/*", "dbscripts/*"]
precision = 2
show_missing = true

[tool.coverage.run]
branch = true
command_line = "-m pytest -v tests/ -m 'not integration'"
omit = ["tests/*", ".tox/*", "db-write/*", "db2json/*", "dbscripts/*"]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
