architecture = "x86_64"
management_repo = {directory = "/tmp/test", url = "https://foo.bar"}
package_pool = "/tmp/packages"
source_pool = "/tmp/sources"
package_repo_base = "/tmp"
source_repo_base = "/tmp"

[[repositories]]
name = "foo"
source_pool = "/tmp/sources"

[[repositories]]
name = "bar"
testing = "blubb"
